# Generated by Django 4.2.20 on 2025-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
