# Generated by Django 4.2.20 on 2025-03-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
