# Generated by Django 5.0.1 on 2025-03-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_moviedata_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="image",
            field=models.ImageField(
                default="Images/None/No-img.jpg", upload_to="Images/"
            ),
        ),
    ]
